name: API_Autenticacao_UP

on:
  push:
    branches: [ "develop-rafael" ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/checkout@v1
      - name: Conecta-se ao servidor na AWS
        run: ssh root@172.31.29.23
                     
